// Copyright 2017-2021 @reef-defi/extension-compat-metamask authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@reef-defi/extension-compat-metamask', version: '1.0.10' };
