// Copyright 2017-2021 @reef-defi/extension-chains authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@reef-defi/extension-chains', version: '0.41.2-0' };
