name: PR

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'test', 'build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies and Run ${{ matrix.step }}
        run: |
          yarn install --immutable | grep -v 'YN0013'
          NODE_OPTIONS=--max_old_space_size=4096 yarn ${{ matrix.step }}
