name: PR
on: [pull_request]

jobs:
  pr:
    continue-on-error: true
    strategy:
      matrix:
        step: ['lint', 'test', 'build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: ${{ matrix.step }}
      run: |
        yarn install --immutable
        npm install -g node-gyp
        cd node_modules/usb-detection
        node-gyp rebuild
        cd ..
        yarn ${{ matrix.step }}
